export const dataEx = [
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis dolores qui in repellat cum, quibusdam voluptates, expedita impedit eos nihil tempora vel rem eligendi. Aut temporibus ea quis ipsam iure.",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
    {
      bonus: "xp sur grobe",
      date: "31-12-2022",
      item_name: "Seigle",
      item_quantity: 20,
      item_url: "url image",
    },
    {
      bonus: "xp sur pandala",
      date: "01-01-2023",
      item_name: "Orge",
      item_quantity: 50,
      item_url: "url image",
    },
]